global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Spring Boot application metrics
  - job_name: 'spring-crm'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
